### ISSUE TITLE
Console label

### ISSUE THREAD

**Issue by RenatoGeh** [rilifon/Project-R1#3]
The label on top of each console entity does not accurately (or at all) show the correct number of inputs/outputs.

**Comment by rilifon** [comment]
Maybe write on top of consoles X/Y, where X is the number of inputs it is expecting, and Y is the number of outputs it still has

**Comment by RenatoGeh** [comment]
This will only confuse the user, as consoles are either input or output, not both.

**Comment by rilifon** [comment]
@renatogeh is it interesting to have some indication so that the player can know if a console is output or input? Or leave thar only to the objective text?
